name: elArroyoQuickStart

# See: https://docs.devwithlando.io/tutorials/wordpress.html
recipe: wordpress
config:
  php: '7.3'
  webroot: app
  database: mariadb

# See: https://docs.devwithlando.io/config/services.html
services:
  appserver:
    run_as_root:
      - "chown www-data: -R /app"

# See: https://docs.devwithlando.io/config/events.html
events:
  pre-stop:
    - echo "Database backup..."
    - wp db export dump.sql --path=/dump/
    - echo "Database successfully backed up"
