<?php

/**
 * !! DO NOT EDIT THIS FILE.
 * -------------------------.
 *
 * To change WordPress configuration options, edit the the files found in the
 * `config/` directory.
 *
 * WordPress expects the `wp-config.php` file to be in either the WordPress root
 * directory, or one directory up. For this reason, the `wp-config.php` file
 * must exist in one of these locations.
 *
 * This `wp-config.php` file pulls in all the configuration normally found in
 * this file from the `config/` directory.
 */

require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/environment.php';
require_once ABSPATH . 'wp-settings.php';
